server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  profiles:
    active: server
#    active: client
  application:
    name: integration



ws-url:
#  client: 158.180.94.242:8080
  client: localhost:8080
  server: localhost:8080